language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - build-tools-23.0.1
    - android-23
    - extra-android-support

before_install:
  - chmod +x gradlew
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null

install:
  - true

script: "./gradlew build"