language: android
android:
  components:
    - build-tools-21.1.2
    - android-21

before_script:
  - chmod +x gradlew

after_success:
  - mvn cobertura:cobertura coveralls:report

script: "./gradlew build"